apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-db-demo
spec:
  project: default
  source:
    repoURL: https://github.com/pcg-gcp/pcg-k8s-training-argocd
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
