apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  postgres-user: YXBwdXNlcg==                 # base64 for "appuser"
  postgres-password: cGFzc3dvcmQ=             # base64 for "password"
  postgres-db: YXBwZGI=                       # base64 for "appdb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS message (
      text VARCHAR(100)
    );

    INSERT INTO message (text)
    VALUES ('You fixed it')
    ON CONFLICT DO NOTHING;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
spec:
  template:
    spec:
      containers:
        - name: seed
          image: postgres:16
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-user
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-db
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          command: ["sh", "-c"]
          args:
            - >
              psql -h db -U "$PGUSER" -d "$PGDATABASE" -f /docker-entrypoint-initdb.d/init.sql
      volumes:
        - name: init-script
          configMap:
            name: db-init-script
      restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
  clusterIP: None
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
spec:
  template:
    spec:
      containers:
        - name: seed
          image: postgres:16
          env:
            - name: PGPASSWORD
              value: password
      restartPolicy: OnFailure

